const sampleDB = [
    {
        "titleCode": "ASSENG00367",
        "titleName": "ASSAM TRIBUNE",
        "hindiTitle": "असम ट्रिब्यून",
        "registerSerialNo": "109963",
        "regnNo": "ASSENG/2009/37406",
        "ownerName": "ASSAM TRIBUNE P.LTD",
        "state": "ASS",
        "publicationCityDistrict": "DIBRUGARH",
        "periodity": "D"
    },
    {
        "titleCode": "ASSENG00220",
        "titleName": "CACHAR TRIBUNE",
        "hindiTitle": "कछार ट्रिब्यून",
        "registerSerialNo": "40742",
        "regnNo": "40742/ 81",
        "ownerName": "UJJAL KUMAR DASS",
        "state": "ASS",
        "publicationCityDistrict": "HAILAKANDI",
        "periodity": "W"
    },
    {
        "titleCode": "ASSENG00031",
        "titleName": "THE CONSTRUCTION TRIBUNE",
        "hindiTitle": "द कंस्ट्रक्शन ट्रिब्यून",
        "registerSerialNo": "40988",
        "regnNo": "40988/ 91",
        "ownerName": "RUNIMA BARUA",
        "state": "ASS",
        "publicationCityDistrict": "JORHAT",
        "periodity": "F"
    },
    {
        "titleCode": "ASSENG00017",
        "titleName": "ASSAM TRIBUNE",
        "hindiTitle": "असम ट्रिब्यून",
        "registerSerialNo": "1127",
        "regnNo": "1127/ 57",
        "ownerName": "ASSAM TRIBUNE (P) LTD",
        "state": "ASS",
        "publicationCityDistrict": "KAMRUP METROPOLITAN/ GUWAHATI",
        "periodity": "D"
    },
    {
        "titleCode": "CHAHIN00043",
        "titleName": "DAINIK TRIBUNE",
        "hindiTitle": "दैनिक ट्रिब्यून",
        "registerSerialNo": "32198",
        "regnNo": "32198/ 78",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH",
        "periodity": "D"
    },
    {
        "titleCode": "CHAPUN00259",
        "titleName": "PUNJABI TRIBUNE",
        "hindiTitle": "पंजाबी ट्रिब्यून",
        "registerSerialNo": "32197",
        "regnNo": "32197/ 78",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH",
        "periodity": "D"
    },
    {
        "titleCode": "CHAENG01062",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "15",
        "regnNo": "15/ 57",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH",
        "periodity": "D"
    },
    {
        "titleCode": "CHAENG01136",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "145158",
        "regnNo": "CHAENG/2017/72603",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT BATHINDA",
        "periodity": "D"
    },
    {
        "titleCode": "CHAPUN00309",
        "titleName": "PUNJABI TRIBUNE",
        "hindiTitle": "पंजाबी ट्रिब्यून",
        "registerSerialNo": "145162",
        "regnNo": "CHAPUN/2017/72607",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT BATHINDA",
        "periodity": "D"
    },
    {
        "titleCode": "CHAHIN00455",
        "titleName": "DAINIK TRIBUNE",
        "hindiTitle": "दैनिक ट्रिब्यून",
        "registerSerialNo": "145254",
        "regnNo": "CHAHIN/2017/72699",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT BATHINDA)",
        "periodity": "D"
    },
    {
        "titleCode": "CHAPUN00308",
        "titleName": "PUNJABI TRIBUNE",
        "hindiTitle": "पंजाबी ट्रिब्यून",
        "registerSerialNo": "145161",
        "regnNo": "CHAPUN/2017/72606",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT GURGAON)",
        "periodity": "D"
    },
    {
        "titleCode": "CHAHIN00454",
        "titleName": "DAINIK TRIBUNE",
        "hindiTitle": "दैनिक ट्रिब्यून",
        "registerSerialNo": "145253",
        "regnNo": "CHAHIN/2017/72698",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT GURGAON)",
        "periodity": "D"
    },
    {
        "titleCode": "CHAENG01138",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "145160",
        "regnNo": "CHAENG/2017/72605",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT GURGAON)",
        "periodity": "D"
    },
    {
        "titleCode": "CHAPUN00310",
        "titleName": "PUNJABI TRIBUNE",
        "hindiTitle": "पंजाबी ट्रिब्यून",
        "registerSerialNo": "145163",
        "regnNo": "CHAPUN/2017/72608",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT JALANDHAR)",
        "periodity": "D"
    },
    {
        "titleCode": "CHAENG01137",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "145159",
        "regnNo": "CHAENG/2017/72604",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "CHA",
        "publicationCityDistrict": "CHANDIGARH(PRINTED AT JALANDHAR)",
        "periodity": "D"
    },
    {
        "titleCode": "CHHHIN00250",
        "titleName": "RASHTRIYA HIND TRIBUNE",
        "hindiTitle": "राष्ट्रीय हिन्द ट्रिब्यून",
        "registerSerialNo": "81601",
        "regnNo": "CHHHIN/2003/09044",
        "ownerName": "NANDINI CHANDRAKAR",
        "state": "CHH",
        "publicationCityDistrict": "RAIPUR",
        "periodity": "Q"
    },
    {
        "titleCode": "DELENG11115",
        "titleName": "DELHI TRIBUNE",
        "hindiTitle": "डेल्ही ट्रिब्यून",
        "registerSerialNo": "66566",
        "regnNo": "66566/ 97",
        "ownerName": "MAYA ENTERPRISES",
        "state": "DEL",
        "publicationCityDistrict": "DELHI",
        "periodity": "D"
    },
    {
        "titleCode": "DELENG08314",
        "titleName": "INDIAN MEDICAL TRIBUNE",
        "hindiTitle": "इंडियन मेडिकल ट्रिब्यून",
        "registerSerialNo": "55745",
        "regnNo": "55745/ 93",
        "ownerName": "DR.J.K. JAIN",
        "state": "DEL",
        "publicationCityDistrict": "DELHI",
        "periodity": "W"
    },
    {
        "titleCode": "DELENG08892",
        "titleName": "THE INTERTRADE TRIBUNE",
        "hindiTitle": "द इंटरट्रेड ट्रिब्यून",
        "registerSerialNo": "68776",
        "regnNo": "68776/ 98",
        "ownerName": "OM PRAKASH PANWAR 'NISHANT'",
        "state": "DEL",
        "publicationCityDistrict": "DELHI",
        "periodity": "W"
    },
    {
        "titleCode": "HARHIN10942",
        "titleName": "SIRSA TRIBUNE",
        "hindiTitle": "सिरसा ट्रिब्यून",
        "registerSerialNo": "38372",
        "regnNo": "38372/ 81",
        "ownerName": "SURENDER BHATIA",
        "state": "HAR",
        "publicationCityDistrict": "SIRSA",
        "periodity": "F"
    },
    {
        "titleCode": "HPENG00130",
        "titleName": "HIMACHAL TRIBUNE",
        "hindiTitle": "हिमाचल ट्रिब्यून",
        "registerSerialNo": "72573",
        "regnNo": "HPENG/1998/00016",
        "ownerName": "DEV PANTHI",
        "state": "HP",
        "publicationCityDistrict": "SHIMLA",
        "periodity": "W"
    },
    {
        "titleCode": "HPHIN00399",
        "titleName": "HIMACHAL TRIBUNE",
        "hindiTitle": "हिमाचल ट्रिब्यून",
        "registerSerialNo": "76819",
        "regnNo": "HPHIN1998/04262",
        "ownerName": "DEV KUMAR PANDHI",
        "state": "HP",
        "publicationCityDistrict": "SHIMLA",
        "periodity": "W"
    },
    {
        "titleCode": "HPHIN00155",
        "titleName": "NATIONAL TRIBUNE",
        "hindiTitle": "नेशनल ट्रिब्यून",
        "registerSerialNo": "34127",
        "regnNo": "34127/ 82",
        "ownerName": "HRIDESH ARYA",
        "state": "HP",
        "publicationCityDistrict": "SIMLA",
        "periodity": "D"
    },
    {
        "titleCode": "JKURD01036",
        "titleName": "KASHMIR TRIBUNE",
        "hindiTitle": "कश्मीर ट्रिब्यून",
        "registerSerialNo": "108167",
        "regnNo": "JKURD/2010/35610",
        "ownerName": "JAWAID AHMAD DAR",
        "state": "JK",
        "publicationCityDistrict": "BARAMULA",
        "periodity": "W"
    },
    {
        "titleCode": "JKENG00845",
        "titleName": "KASHMIR TRIBUNE",
        "hindiTitle": "कश्मीर ट्रिब्यून",
        "registerSerialNo": "113608",
        "regnNo": "JKENG/2011/41051",
        "ownerName": "JAWAID AHMAD DAR",
        "state": "JK",
        "publicationCityDistrict": "BARAMULLA",
        "periodity": "W"
    },
    {
        "titleCode": "JKENG01230",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "142198",
        "regnNo": "JKENG/2016/69643",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "JK",
        "publicationCityDistrict": "JAMMU",
        "periodity": "D"
    },
    {
        "titleCode": "JKENG01059",
        "titleName": "THE TRIBUNE",
        "hindiTitle": "द ट्रिब्यून",
        "registerSerialNo": "126847",
        "regnNo": "JKENG/2013/54292",
        "ownerName": "THE TRIBUNE TRUST",
        "state": "JK",
        "publicationCityDistrict": "SRINAGAR",
        "periodity": "D"
    },
    {
        "titleCode": "JKURD01095",
        "titleName": "SRINAGAR TRIBUNE",
        "hindiTitle": "श्रीनगर ट्रिब्यून",
        "registerSerialNo": "122284",
        "regnNo": "JKURD/2013/49729",
        "ownerName": "BILAL AHMAD",
        "state": "JK",
        "publicationCityDistrict": "SRINAGAR",
        "periodity": "W"
    },
    {
        "titleCode": "KERENG00780",
        "titleName": "INDUSTRIAL AND CULTURAL TRIBUNE",
        "hindiTitle": "इंडस्ट्रियल एंड कल्चरल ट्रिब्यून",
        "registerSerialNo": "7786",
        "regnNo": "7786/ 64",
        "ownerName": "C K PILLAY",
        "state": "KER",
        "publicationCityDistrict": "ERNAKULAM",
        "periodity": "M"
    },
    {
        "titleCode": "MAHENG04289",
        "titleName": "GOAN TRIBUNE",
        "hindiTitle": "गोअन ट्रिब्यून",
        "registerSerialNo": "6030",
        "regnNo": "6030/ 57",
        "ownerName": "TRIBUNE(BOMBAY) PRIVATE LTD",
        "state": "MAH",
        "publicationCityDistrict": "MUMBAI",
        "periodity": "F"
    },
    {
        "titleCode": "MAHENG05869",
        "titleName": "THE BOMBAY TRIBUNE",
        "hindiTitle": "द बॉम्बे ट्रिब्यून",
        "registerSerialNo": "59911",
        "regnNo": "59911/ 95",
        "ownerName": "ASHOK GARG",
        "state": "MAH",
        "publicationCityDistrict": "MUMBAI",
        "periodity": "W"
    },
    {
        "titleCode": "MAHENG07429",
        "titleName": "THE U P LAW TRIBUNE",
        "hindiTitle": "द यू पी लॉ ट्रिब्यून",
        "registerSerialNo": "35721",
        "regnNo": "35721/ 79",
        "ownerName": "ALL INDIA REPORTER LTD.",
        "state": "MAH",
        "publicationCityDistrict": "NAGPUR",
        "periodity": "M"
    },
    {
        "titleCode": "MAHENG14048",
        "titleName": "HOUSING TRIBUNE",
        "hindiTitle": "",
        "registerSerialNo": "24249",
        "regnNo": "24249/ 74",
        "ownerName": "SAMAJ SHIKSHAN AND SEVA MANDAL",
        "state": "MAH",
        "publicationCityDistrict": "PUNE",
        "periodity": "Q"
    },
    {
        "titleCode": "MAHMAR11969",
        "titleName": "PUNE TRIBUNE",
        "hindiTitle": "पुणे ट्रिब्यून",
        "registerSerialNo": "59814",
        "regnNo": "59814/ 94",
        "ownerName": "ANGELS SALES & MARKETING PVT. LTD.",
        "state": "MAH",
        "publicationCityDistrict": "PUNE",
        "periodity": "W"
    },
    {
        "titleCode": "MAHMAR14559",
        "titleName": "YAVATMAL TRIBUNE",
        "hindiTitle": "यवतमाल ट्रिब्यून",
        "registerSerialNo": "70268",
        "regnNo": "70268/ 96",
        "ownerName": "J.B. SONONE",
        "state": "MAH",
        "publicationCityDistrict": "YAVATMAL",
        "periodity": "W"
    },
    {
        "titleCode": "MPHIN37294",
        "titleName": "CAPITAL TRIBUNE",
        "hindiTitle": "कैपिटल ट्रिब्यून",
        "registerSerialNo": "157655",
        "regnNo": "MPHIN/2021/85100",
        "ownerName": "SANTOSH SAHU",
        "state": "MP",
        "publicationCityDistrict": "BHOPAL",
        "periodity": "W"
    },
    {
        "titleCode": "PUNURD00350",
        "titleName": "THE LUDHIANA TRIBUNE",
        "hindiTitle": "द लुधियाना ट्रिब्यून",
        "registerSerialNo": "33864",
        "regnNo": "33864/ 79",
        "ownerName": "RAJINDER KUMAR JAIN",
        "state": "PUN",
        "publicationCityDistrict": "LUDHIANA",
        "periodity": "F"
    },
    {
        "titleCode": "TELENG00315",
        "titleName": "BANJARA TRIBUNE",
        "hindiTitle": "बंजारा ट्रिब्यून",
        "registerSerialNo": "27703",
        "regnNo": "27703/ 76",
        "ownerName": "RAVINDRA NAIK",
        "state": "TEL",
        "publicationCityDistrict": "HYDERABAD",
        "periodity": "W"
    },
    {
        "titleCode": "UPHIN19653",
        "titleName": "NISHPAKSH AVADH TRIBUNE",
        "hindiTitle": "निष्पक्ष अवध ट्रिब्यून",
        "registerSerialNo": "59571",
        "regnNo": "59571/ 94",
        "ownerName": "S.R.PUBLICATION",
        "state": "UP",
        "publicationCityDistrict": "BARABANKI",
        "periodity": "W"
    },
    {
        "titleCode": "UPENG00860",
        "titleName": "NATIONAL TRIBUNE",
        "hindiTitle": "नेशनल ट्रिब्यून",
        "registerSerialNo": "9899",
        "regnNo": "9899/ 66",
        "ownerName": "C.M SADRI",
        "state": "UP",
        "publicationCityDistrict": "KANPUR",
        "periodity": "W"
    },
    {
        "titleCode": "UPHIN26037",
        "titleName": "AVADH TRIBUNE",
        "hindiTitle": "अवध ट्रिब्यून",
        "registerSerialNo": "35616",
        "regnNo": "35616/ 80",
        "ownerName": "SATYA PRAKASH SRIVASTAVA",
        "state": "UP",
        "publicationCityDistrict": "LUCKNOW",
        "periodity": "F"
    },
    {
        "titleCode": "UPENG03764",
        "titleName": "THE LUCKNOW TRIBUNE",
        "hindiTitle": "द लखनऊ ट्रिब्यून",
        "registerSerialNo": "120785",
        "regnNo": "UPENG/2012/48229",
        "ownerName": "RAJNISH CHOPRA",
        "state": "UP",
        "publicationCityDistrict": "LUCKNOW",
        "periodity": "W"
    },
    {
        "titleCode": "UPHIN26537",
        "titleName": "HINDI TRIBUNE",
        "hindiTitle": "हिंदी ट्रिब्यून",
        "registerSerialNo": "13505",
        "regnNo": "13505/ 67",
        "ownerName": "AKHILANAND ARYA",
        "state": "UP",
        "publicationCityDistrict": "LUCKNOW",
        "periodity": "W"
    },
    {
        "titleCode": "UPENG00865",
        "titleName": "NEPAL TRIBUNE",
        "hindiTitle": "नेपाल ट्रिब्यून",
        "registerSerialNo": "12668",
        "regnNo": "12668/ 66",
        "ownerName": "PUSPA LAL",
        "state": "UP",
        "publicationCityDistrict": "VARANASI",
        "periodity": "M"
    },
    {
        "titleCode": "UTTENG00173",
        "titleName": "THE UTTARAKHAND TRIBUNE",
        "hindiTitle": "दि उत्तराखण्ड ट्रिब्यून",
        "registerSerialNo": "141179",
        "regnNo": "UTTENG/2011/68624",
        "ownerName": "SHIVAM BISHT",
        "state": "UTT",
        "publicationCityDistrict": "DEHRADUN",
        "periodity": "W"
    },
    {
        "titleCode": "WBENG03332",
        "titleName": "INDUSTRIAL TRIBUNE",
        "hindiTitle": "इंडस्ट्रियल ट्रिब्यून",
        "registerSerialNo": "13752",
        "regnNo": "13752/ 67",
        "ownerName": "KASHINATHH LAHIRI",
        "state": "WB",
        "publicationCityDistrict": "BARDHAMAN",
        "periodity": "F"
    },
    {
        "titleCode": "WBENG02280",
        "titleName": "COAL FIELD TRIBUNE",
        "hindiTitle": "कोल फील्ड ट्रिब्यून",
        "registerSerialNo": "5478",
        "regnNo": "5478/ 62",
        "ownerName": "DAMODAR GUPTA",
        "state": "WB",
        "publicationCityDistrict": "BARDHAMAN",
        "periodity": "W"
    },
    {
        "titleCode": "WBBEN08414",
        "titleName": "ASANSOL DURGAPUR TRIBUNE",
        "hindiTitle": "आसनसोल दुर्गापुर ट्रिब्यून",
        "registerSerialNo": "53217",
        "regnNo": "53217/ 92",
        "ownerName": "DULAL MONDAL",
        "state": "WB",
        "publicationCityDistrict": "BARDHMAN/ DURGAPUR",
        "periodity": "W"
    },
    {
        "titleCode": "WBENG01884",
        "titleName": "SPORTS TRIBUNE",
        "hindiTitle": "स्पोर्ट्स ट्रिब्यून",
        "registerSerialNo": "18370",
        "regnNo": "18370/ 70",
        "ownerName": "KISHORE BHIMANI",
        "state": "WB",
        "publicationCityDistrict": "KOLKATA",
        "periodity": "W"
    }
];

module.exports = { data: sampleDB };